server:
  port: 8081

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  application:
    name: app-mvc-gestao

  cloud:
    openfeign:
      okhttp:
        enabled: true



api:
  central:
    url: http://localhost:8080
